### PR TITLE
Add multipart downloading support

### PR DESCRIPTION
**Pull request by monkey2000**
Fix Issue #240

Once the file is too small or the server does not support HTTP RANGE parameter, it will be fallback to single.

### CODE REVIEW

**Comment by monkey2000** [comment]
testKnn(org.wikibrain.spatial.distance.TestGeodeticDistanceMetric) from module wikibrain-spatial.

**Comment by monkey2000** [comment]
Knn Test from module wikibrain-spatial has failed.

**Comment by shilad** [comment]
Clearly that KNN test failure is not related to this. I think it's actually related to a fix from another PR. I'm going to merge and look into it. Thanks for the contribution!

**Comment by monkey2000** [comment]
It's my pleasure to contribute with such a exciting project.

**Pull request merged**
